const RouterConfig = {
    DashboardPage: '/',
    LandingPage: '/landing',
    LoginLoadingPage: '/loading',
    PendingUserPage: '/pending',
    TogetherTimeLayout: '/together-time',
    Members: '/together-time/members',
    Member: (id: string | null) => `/together-time/members/${id ?? `:id`}`,
    TogetherFeed: `feed`, // relative paths can't start with / (feed = /togetherTime/feed)
    Activities: `/together-time/activities`,
    Activity: (id: string | null) => `/together-time/activities/${id ?? `:id`}`,
    Medications: '/medications',
    Medication: (id: string | null) => `/medications/${id ?? `:id`}`,
    RefillMedicationPage: '/medications/refill',
    PageNotFound: '*',
    CarePlan: '/care-plan/profile',
    Documents: '/care-plan/documents',
    Document: (id: string | null) => `/care-plan/documents/${id ?? `:id`}`,
    DocumentAnswer: (id: string | null) => `/care-plan/document-answers/${id ?? `:id`}`,
    Profile: '/care-plan/',
    Conditions: '/care-plan/conditions/',
    Providers: '/care-plan/providers',
    Condition: (id: string | null) => `/care-plan/conditions/${id ?? `:id`}`,
    Provider: (id: string | null) => `/care-plan/providers/${id ?? `:id`}`,
    Pharmacies: '/care-plan/pharmacies',
    Pharmacy: (id: string | null) => `/care-plan/pharmacies/${id ?? `:id`}`,
    Immunizations: '/care-plan/immunizations',
    Immunization: (id: string | null) => `/care-plan/immunizations/${id ?? `:id`}`,
    TermsOfService: '/terms-of-service',
    TermsSuccess: '/terms-success',
    TermsSuccessFAQ: '/terms-success/FAQ',
    NotificationsSubscribe: '/notifications-subscribe',
    GetStarted: '/get-started',
    FAQ: '/FAQ',
    Allergies: '/care-plan/allergies',
    Allergy: (id: string | null) => `/care-plan/allergies/${id ?? `:id`}`,
    EmergencyContacts: '/care-plan/emergency-contacts',
    RecipientProfile: '/care-plan/recipient-profile',
    Goals: '/goals',
    GetStartedRecipientProfile: '/get-started/recipient-profile',
    GoalInfoCarePlan: '/goal-info-care-plan',
    GoalInfoMedManager: '/goal-info-medications',
    GoalInfoTogetherTimeMember: '/goal-info-together-time-member',
    GoalInfoTogetherTimeAdmin: '/goal-info-together-time-admin',
    Home: '/home',
    Question: '/home/question',
    Calendar: '/calendar',
    Appointment: (id: string | null) => `/calendar/appointments/${id ?? `:id`}`,
    Annotations: '/annotations',
    Annotation: (id: string | null) => `/annotations/${id ?? `:id`}`,
    Timeline: '/care-plan/timeline',
};

export default RouterConfig;
