export const ERROR_MESSAGES = {
    GENERIC_ERROR: 'Something went wrong. Please try again later.',
    APP_INVITATION_INFO: `We couldn't find a care circle associated with the given invite code.
    Please reach out to the care circle owner for a new invite code.`,
    AUTH_ERROR: 'We ran into an issue authenticating your account. Please try to log in again.',
    CREATE_ACCOUNT: 'We ran into an issue creating your account. Please try to log in again.',
    CREATE_CARE_CIRCLE: 'We ran into an issue creating your care circle. Please try to log in again.',
    DELETE_CARE_CIRCLE: 'We ran into an issue clearing you care circle data.',
    EMAIL_ERROR: 'We ran into an issue sending your invitation. Please try again.',
    REVOKE_ERROR: 'We ran into an issue revoking the invitation. Please try again.',
    APPROVE_ERROR: 'We ran into an issue approving the invitation. Please try again.',
    REJECT_ERROR: 'We ran into an issue rejecting the invitation. Please try again.',
    INVITE_CODE_CORRUPTED: 'We ran into an issue adding you to a care circle. Please try to log in again.',
    NO_MEDICATIONS_PERMISSIONS: `We're sorry, you don't have permission to view that page.`,
    JOIN_CARE_CIRCLE_FROM_INVITE_LINK: 'We ran into an issue adding you to the care circle. Please try again.',
    PERMISSIONS_ERROR: 'We ran into an issue validating your permissions. Please logout and log back in.',
    USER_INFO: 'We ran into an issue getting your user data. Please try to log in again.',
    USER_AUTHENTICATION: 'Error authenticating user',
    GET_CARE_CIRCLE: 'Something went wrong. Please try again later.',
    SEARCH_MEDICATION: 'Something went wrong. Please try again later.',
    SEARCH_PROVIDER: 'Something went wrong. Please try again later.',
    EDIT_PROVIDER: 'Something went wrong. Please try again later.',
    ADD_PROVIDER: 'Something went wrong. Please try again later.',
    GET_PROVIDERS: 'Something went wrong. Please try again later.',
    SEARCH_PHARMACY: 'Something went wrong. Please try again later.',
    EDIT_PHARMACY: 'Something went wrong. Please try again later.',
    ADD_PHARMACIES: 'Something went wrong. Please try again later.',
    GET_PHARMACIES: 'Something went wrong. Please try again later.',
    SEARCH_ADDRESS: 'Something went wrong. Please try again later.',
    ADD_MEMBER_ERROR: 'There was an error adding this team member',
    GET_CONDITIONS: 'Something went wrong. Please try again later.',
    GET_IMMUNIZATIONS: 'Something went wrong. Please try again later.',
    ADD_IMMUNIZATION: 'Something went wrong. Please try again later.',
    SEARCH_IMMUNIZATION: 'Something went wrong. Please try again later.',
    EDIT_IMMUNIZATION: 'Something went wrong. Please try again later.',
    GET_ALLERGIES: 'Something went wrong. Please try again later.',
    ADD_ALLERGY: 'Something went wrong. Please try again later.',
    SEARCH_ALLERGY: 'Something went wrong. Please try again later.',
    EDIT_ALLERGY: 'Something went wrong. Please try again later.',
    SEARCH_CONDITION: 'Something went wrong. Please try again later.',
    SIGNED_OUT: 'You have been signed out. Please Sign In Again',
    UPLOAD_PHOTO: 'We ran into an issue uploading your photo. Please try again later.',
    CREATE_CARE_RECIPIENT: 'We ran into an issue creating your care recipient. Please try again later.',
    GET_CARE_RECIPIENT: 'Something went wrong. Please try again later.',
    EDIT_CARE_RECIPIENT: 'Something went wrong. Please try again later.',
    EDIT_ACTIVITY: 'Something went wrong. Please try again later.',
    GET_TIMEZONES: 'We ran into an issue fetching time zone data.',
    NOTIFICATIONS_DISPLAY_ERROR: 'Something went wrong. Please try again later.',
    NOTIFICATIONS_UPDATE: 'We ran into an issue updating your preferences. Please try again later.',
    ADD_APPOINTMENT: 'Something went wrong. Please try again later.',
    EDIT_APPOINTMENT: 'Something went wrong. Please try again later.',
};

export const LOCAL_STORAGE_KEYS = {
    HAS_REQUESTED_MS_GRAPH_CONSENT: 'hasRequestedMsGraphConsent',
    INVITE_CODE: 'inviteCode',
    CARE_CIRCLE_ID: 'careCircleId',
    AUTH_ERROR: 'authError',
    ROLE: 'role',
    INVITES_PENDING: 'invitesPending',
    AGREE_CONSENT_TO_MANAGE_HEALTH: 'agreesHasConsentToManageLoveOnesHealth',
    AGREE_TO_TOS: 'agreesToTermsAndPrivacy',
    AGREE_UNDERSTANDS_USAGE: 'understandsIntendedAppUse',
    AGREE_UNDERSTANDS_DATA_USE: 'understandsMicrosoftUseOfTheirData',
    UNDERSTANDS_MINORS_NOT_PERMITTED: 'understandsNotPermittedToUsePlatformForMinors',
    AGREE_TO_OPENAI: 'agreesToOpenAiUse',
    RECIPIENT_NAME_GIVEN: 'gaveRecipientName',
    MAX_HEIGHT: 'maxHeight',
    HAS_ONBOARDED: 'hasOnboarded',
    HOME_PAGE_FEATURE_FLAG: 'homePage',
    ANNOTATION_FEATURE_FLAG: 'annotationFeatureFlag',
    WELCOME_MESSAGE_FEATURE_FLAG: 'welcomeMessageFeatureFlag',
    TODAY_VIEW_FEATURE_FLAG: 'todayViewFeatureFlag',
    SIX_MONTH_TOOLKIT_FEATURE_FLAG: 'sixMonthToolkitFeatureFlag',
    SUGGESTED_ARTICLE_FEATURE_FLAG: 'suggestedArticleFeatureFlag',
    POSITIVITY_SLOT_FEATURE_FLAG: 'positivitySlotFeatureFlag',
};

export const USER_MESSAGES = {
    COPY_LINK_SUCCESS: 'Paste in an email or text',
    COPY_LINK_TITLE: 'Copied to Clipboard',
    EMAIL_SUCCESS: 'Email sent successfully.',
    INVITATION_SUCCESS: 'Invitation sent.',
    CANCELLED_INVITATION: 'Cancelled Invitation',
    CANCELLED_SUCCESSFUL: 'You have successfully cancelled a Care Circle invitation',
    INVITATION_APPROVED: 'Invitation approved.',
    INVITATION_REJECTED: 'Invitation rejected.',
    LOADING_DIALOG: 'Give us a moment while we get things ready for you...',
    PENDING_DIALOG: 'It will take a moment or two for the admin to verify your identity. Check back later.',
    LOADING_PROFILE_TEXT: 'Your Profile',
    LOADING_SPINNER: 'Loading...',
};

export const USER_INPUT_PLACEHOLDERS = {
    EMPTY_TIMES_A_DAY_TEXT: 'How many times a day is this taken?',
};
